### PR TITLE
Update MapBuilder Page - WIP

### PR DESCRIPTION
**Pull request by richardbarad**
Updating text in MapBuilder developer page

### CODE REVIEW

**Comment by richardbarad** [comment]
@edbrett and @simaob.

I made some changes to the text on GFW MapBuilder page of the GFW site. Could you please review the updates and push to staging? 

Many thanks!

Best,

Richard

**Review by edbrett — APPROVED** [review]
All looks good to me! Thanks @richardbarad 🎖

**Comment by richardbarad** [comment]
Thanks @edbrett! What is the next step to deploy these updates to the staging site?

**Comment by edbrett** [comment]
It has been deployed, but github pages something has issues with clearing cache.

**Comment by richardbarad** [comment]
@edbrett. Thanks! Where is the link to see it on staging? 

The following workflow seems to direct me to the production site where the updates are not visible even in an incognito window. 

1) Go to **https://staging.globalforestwatch.org/**
2) Click More, then Developer tools
3) Click Map-Builder in the tabs

I end up on this links which seems to be the live site: https://developers.globalforestwatch.org/map-builder/

Or was this deployed to live and we just need to wait for the cache to clear?

Best,

Richard

**Comment by edbrett** [comment]
There is no staging for this app as it is isolated from flagship. The updates have been deployed to prod but I can't seem to get the cache to clear. I will let you know once I've got it working.

**Comment by edbrett** [comment]
Ok, the cache has finally cleared and it is all live!

**Comment by richardbarad** [comment]
@edbrett. Looks good. Thanks! We are standardizing the spelling of MapBuilder to not include a space so I am going to update this in a few other places in the developer section via a new pull request. I realized MapBuilder is referenced in the Gallery and Developer tool section as well.

**Pull request merged**
